name: Build Unity APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/lib/jvm
        df -h

    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.12f1
        targetPlatform: Android

    - name: Build Project
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.12f1
        targetPlatform: Android

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyGame-APK
        path: build/Android/*.apk
